language: cpp

env:
  global:
    - OMP_NUM_THREADS=4
    -

addons:
  homebrew:
    brewfile: true
    update: true
  apt:
    sources:
    update: true
    packages:
      - libopenblas-dev
      - liblapack3
      - liblapack-dev
      - clang
      - libssl-dev
      - swig

matrix:
  include:
    - os: linux
      compiler: clang
      env:
        - PYTHON_VERSION=2.7
        # NOTE: Hack, c.f. https://github.com/travis-ci/travis-ci/issues/8613
        - LD_LIBRARY_PATH="/usr/local/clang/lib"
    - os: linux
      compiler: clang
      env:
        - PYTHON_VERSION=3.5
        # NOTE: Hack, c.f. https://github.com/travis-ci/travis-ci/issues/8613
        - LD_LIBRARY_PATH="/usr/local/clang/lib"
    - os: linux
      compiler: clang
      env:
        - PYTHON_VERSION=3.6
        # NOTE: Hack, c.f. https://github.com/travis-ci/travis-ci/issues/8613
        - LD_LIBRARY_PATH="/usr/local/clang/lib"
    - os: linux
      compiler: clang
      env:
        - PYTHON_VERSION=3.7
        # NOTE: Hack, c.f. https://github.com/travis-ci/travis-ci/issues/8613
        - LD_LIBRARY_PATH="/usr/local/clang/lib"

before_install:
  - eval "$MATRIX_EVAL"
  - |
    if [ "$TRAVIS_OS_NAME" == "osx" ]; then
      export PATH="/Users/travis/.pyenv/shims:${PATH}"
      export CC=/usr/local/opt/llvm/bin/clang CXX=/usr/local/opt/llvm/bin/clang++
    fi
  - git clone https://github.com/momo-lab/xxenv-latest.git "$(pyenv root)"/plugins/xxenv-latest
  - pyenv latest install $PYTHON_VERSION -f
  - pyenv latest global $PYTHON_VERSION
  - export PYTHON_CFLAGS="$(python-config --includes)"
  - pip install --upgrade pip
  - pip install numpy wheel

install:
  - cd faiss/
  - ./.travis/install.sh
  - aclocal
  - autoconf
  - ./configure --without-cuda
  - make
  - make -C python

script:
  - make test

