language: cpp
compiler: clang
osx_image: xcode10.1
sudo: true
dist: xenial

os:
  - linux
  - osx

env:
  global:
    - OMP_NUM_THREADS=4
    - HOMEBREW_NO_INSTALL_CLEANUP=1
    # NOTE: Hack, c.f. https://github.com/travis-ci/travis-ci/issues/8613
    - LD_LIBRARY_PATH="/usr/local/clang/lib"
  matrix:
    - PYTHON_VERSION=2.7
    - PYTHON_VERSION=3.5
    - PYTHON_VERSION=3.6
    - PYTHON_VERSION=3.7

addons:
  homebrew:
    brewfile: true
    update: true
  apt:
    sources:
    update: true
    packages:
      - libopenblas-dev
      - liblapack3
      - liblapack-dev
      - clang
      - libssl-dev
      #- swig

matrix:
  include:
    - os: osx
      env: PYTHON_VERSION=2.7
      osx_image: xcode9.4
    - os: osx
      env: PYTHON_VERSION=3.6
      osx_image: xcode9.4
    - os: osx
      env: PYTHON_VERSION=3.5
      osx_image: xcode9.4
    - os: osx
      env: PYTHON_VERSION=3.7
      osx_image: xcode9.4

before_install:
  - eval "$MATRIX_EVAL"
  - |
    if [ "$TRAVIS_OS_NAME" == "osx" ]; then
      export PATH="/Users/travis/.pyenv/shims:${PATH}"
      export CC=/usr/local/opt/llvm/bin/clang CXX=/usr/local/opt/llvm/bin/clang++
    fi
  - |
    if [ "$TRAVIS_OS_NAME" == "linux" ]; then
      cd /opt/pyenv/ && git fetch && git checkout v1.2.11 && cd -
    fi
  - git clone https://github.com/momo-lab/xxenv-latest.git "$(pyenv root)"/plugins/xxenv-latest
  - pyenv latest install $PYTHON_VERSION -f
  - pyenv latest global $PYTHON_VERSION
  - export PYTHON_CFLAGS="$(python-config --includes)"
  - pip install --upgrade pip
  - pip install numpy wheel

install:
  - cd faiss/
  - ./.travis/install.sh
  - aclocal
  - autoconf
  - ./configure --without-cuda
  - make -j2
  - make -C python

script:
  - make test
  - make misc/test_blas && ./misc/test_blas
  - cd python/
  - python -c "import faiss, numpy; faiss.Kmeans(10, 20).train(numpy.random.rand(1000, 10).astype('float32'))"

after_script:
  - cp $TRAVIS_BUILD_DIR/setup.py .
  - |
  cat <<EOF > setup.cfg
  [bdist_wheel]
  universal = false
  plat-name=$(python -c "from wheel.pep425tags import get_platform; print(get_platform().replace('linux', 'manylinux1'))")
  EOF
  - cat setup.cfg
  - python setup.py bdist_wheel
