language: cpp

env:
  global:
    - OMP_NUM_THREADS=4

addons:
  homebrew:
    brewfile: true
    update: true
  apt:
    sources:
    update: true
    packages:
    - libopenblas-dev
    - liblapack3
    - liblapack-dev
    - clang
    - libssl-dev
    - swig

matrix:
  include:
    - os: linux
      compiler: clang
      env:
        - PYTHON_VERSION=2.7
        - PYTHON_CFLAGS="-I/usr/include/python2.7"
        # NOTE: Hack, c.f. https://github.com/travis-ci/travis-ci/issues/8613
        - LD_LIBRARY_PATH="/usr/local/clang/lib"
    - os: osx
      env:
        - MATRIX_EVAL="brew update && brew install gcc@6 numpy swig; brew link --overwrite gcc@6; export CC=gcc-6 CXX=g++-6"
    - os: osx
      env:
        - MATRIX_EVAL="brew update && brew install llvm numpy swig; brew link --overwrite llvm; export CC=/usr/local/opt/llvm/bin/clang CXX=/usr/local/opt/llvm/bin/clang++"
        - LDFLAGS="-L/usr/local/opt/llvm/lib"
        - CPPFLAGS="-I/usr/local/opt/llvm/include"
  allow_failures:
    - os: osx
      env:
        - MATRIX_EVAL="brew update && brew install gcc@6 numpy swig; brew link --overwrite gcc@6; export CC=gcc-6 CXX=g++-6"

before_install:
  - eval "$MATRIX_EVAL"

install:
  - ./faiss/.travis/install.sh
  - |
    if [ "$TRAVIS_OS_NAME" == "osx" ]; then
      export PATH="/Users/travis/.pyenv/shims:${PATH}"
      export CC=/usr/local/opt/llvm/bin/clang CXX=/usr/local/opt/llvm/bin/clang++
    fi
  - git clone https://github.com/momo-lab/xxenv-latest.git "$(pyenv root)"/plugins/xxenv-latest
  - pyenv latest install $PYTHON_VERSION
  - pyenv latest global $PYTHON_VERSION
  - export PYTHON_CFLAGS="$(python-config --includes)"
  - pip install --upgrade pip
  - pip install numpy wheel
  - aclocal
  - autoconf
  - ./configure --without-cuda
  - make
  - make -C python

script:
  - make test

